# Generated by Django 6.0 on 2026-01-06 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("theory", "Theory"),
                            ("quiz", "Quiz"),
                            ("practice", "Practice"),
                        ],
                        default="theory",
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order within the module"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "lessons",
                "ordering": ["module__order", "order"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order of the module"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "modules",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LessonUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("audio", "Audio"),
                            ("image", "Image"),
                            ("notation", "Notation"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        blank=True, help_text="JSON content for the unit", null=True
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order within the lesson"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="lessons.lesson",
                    ),
                ),
            ],
            options={
                "db_table": "lesson_units",
                "ordering": ["lesson__order", "order"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="lessons.module",
            ),
        ),
        migrations.CreateModel(
            name="Notation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measure_number", models.PositiveIntegerField(default=1)),
                (
                    "note",
                    models.CharField(
                        help_text="Note name (e.g., C4, D5, E3)", max_length=10
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        help_text="Note duration (whole, half, quarter, eighth)",
                        max_length=20,
                    ),
                ),
                (
                    "clef",
                    models.CharField(
                        choices=[("treble", "Treble"), ("bass", "Bass")],
                        default="treble",
                        max_length=10,
                    ),
                ),
                (
                    "accidental",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("sharp", "Sharp"),
                            ("flat", "Flat"),
                            ("natural", "Natural"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "start_beat",
                    models.FloatField(
                        default=1.0, help_text="Starting beat position in the measure"
                    ),
                ),
                (
                    "is_rest",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is a rest instead of a note",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of notes in the notation"
                    ),
                ),
                (
                    "lesson_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notations",
                        to="lessons.lessonunit",
                    ),
                ),
            ],
            options={
                "db_table": "notations",
                "ordering": ["measure_number", "order"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quiz_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("match_the_following", "Match the Following"),
                        ],
                        default="multiple_choice",
                        max_length=30,
                    ),
                ),
                (
                    "prompt",
                    models.TextField(help_text="Question or instruction for the quiz"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of quiz within the unit"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="lessons.lessonunit",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Quizzes",
                "db_table": "quizzes",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuizOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "match_key",
                    models.CharField(
                        blank=True, help_text="Key for matching pairs", max_length=100
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="lessons.quiz",
                    ),
                ),
            ],
            options={
                "db_table": "quiz_options",
                "ordering": ["order"],
            },
        ),
    ]
