# Generated by Django 6.0 on 2026-01-08 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1, help_text="Part number (1, 2, 3...)"
                    ),
                ),
                (
                    "notes",
                    models.JSONField(help_text="List of notes, e.g. ['C', 'D', 'E']"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sequences",
                        to="lessons.lesson",
                    ),
                ),
            ],
            options={
                "db_table": "practice_sequences",
                "ordering": ["order"],
            },
        ),
    ]
