# Generated by Django 6.0 on 2026-01-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_practicesequence"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessonunit",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="lesson_unit",
        ),
        migrations.RemoveField(
            model_name="quizoption",
            name="quiz",
        ),
        migrations.DeleteModel(
            name="Notation",
        ),
        migrations.DeleteModel(
            name="LessonUnit",
        ),
        migrations.DeleteModel(
            name="Quiz",
        ),
        migrations.DeleteModel(
            name="QuizOption",
        ),
    ]
