# Generated by Django 6.0 on 2026-01-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0003_remove_lessonunit_lesson_remove_quiz_lesson_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicesequence",
            name="sequence_type",
            field=models.CharField(
                choices=[
                    ("listen", "Listen & Repeat"),
                    ("learn", "Learn Note"),
                    ("identify", "Identify Note"),
                    ("read", "Sight Reading"),
                ],
                default="listen",
                help_text="Type of interaction",
                max_length=20,
            ),
        ),
    ]
