# Generated by Django 6.0 on 2026-01-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0004_practicesequence_sequence_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicesequence",
            name="time_signature",
            field=models.CharField(
                default="4/4", help_text="Time Signature (e.g. 4/4)", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="practicesequence",
            name="sequence_type",
            field=models.CharField(
                choices=[
                    ("listen", "Listen & Repeat"),
                    ("learn", "Learn Note"),
                    ("identify", "Identify Note"),
                    ("read", "Sight Reading"),
                    ("play", "Play Mode"),
                ],
                default="listen",
                help_text="Type of interaction",
                max_length=20,
            ),
        ),
    ]
