# Generated by Django 6.0 on 2026-03-11 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0001_initial"),
        ("lessons", "0006_userprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="instrument",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="instruments.instrument",
            ),
        ),
    ]
