# Generated by Django 6.0 on 2026-03-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0007_module_instrument"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicesequence",
            name="lyrics",
            field=models.JSONField(
                blank=True,
                help_text="List of lyrics matching the length of notes, or null",
                null=True,
            ),
        ),
    ]
