# Generated by Django 6.0 on 2026-04-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0009_pitchhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practicesequence",
            name="sequence_type",
            field=models.CharField(
                choices=[
                    ("listen", "Listen & Repeat"),
                    ("learn", "Learn Note"),
                    ("identify", "Identify Note"),
                    ("read", "Sight Reading"),
                    ("play", "Play Mode"),
                    ("perform", "Perform (Scored)"),
                    ("tap", "Tap Mode"),
                    ("place", "Place Note"),
                ],
                default="listen",
                help_text="Type of interaction",
                max_length=20,
            ),
        ),
    ]
