# Generated by Django 6.0 on 2026-03-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="natural_pitch",
            field=models.FloatField(
                blank=True, help_text="User's natural speaking pitch in Hz", null=True
            ),
        ),
    ]
