# Generated by Django 6.0 on 2026-03-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_natural_pitch"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="current_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_active_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
